# Generated by Django 4.2.3 on 2023-07-29 16:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('ingredients', models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(5)])),
                ('instructions', models.TextField(max_length=2500)),
                ('category', models.CharField(choices=[('Main Dish', 'Main Dish'), ('Side Dish', 'Side Dish'), ('Starter', 'Starter'), ('Salad', 'Salad'), ('Soup', 'Soup'), ('Dessert', 'Dessert')], max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
