# Generated by Django 4.2.3 on 2023-07-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
