# Generated by Django 4.2.3 on 2023-07-29 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default=1, max_length=100, validators=[django.core.validators.MinLengthValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(default=1, upload_to='recipe_pics/'),
            preserve_default=False,
        ),
    ]
