# Generated by Django 4.2.3 on 2023-07-29 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_description_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
