# Generated by Django 4.2.3 on 2023-08-08 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=31, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
