# Generated by Django 4.2.3 on 2023-07-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperushuser',
            name='user_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
