# Generated by Django 4.2.3 on 2023-07-31 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_reciperushuser_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperushuser',
            name='user_picture',
        ),
        migrations.AddField(
            model_name='reciperushprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='reciperushprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='reciperushprofile',
            name='user_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reciperushuser',
            name='first_name',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reciperushuser',
            name='last_name',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
