# Generated by Django 4.2.3 on 2023-07-31 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_reciperushuser_user_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reciperushuser',
            managers=[
            ],
        ),
    ]
